club95/auth.py
import os

from flask import Blueprint, render_template, redirect, url_for, request, flash
from .form import LoginForm, RegisterForm
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from flask_login import login_user, logout_user

from . import db


auth_bp = Blueprint('auth_bp', __name__, template_folder='templates')

@auth_bp.route('/auth/register', methods=['GET', 'POST'])
def register():
    # Make the form
    form = RegisterForm()

    # call this line on form post and check for validation against form fields
    if form.validate_on_submit():

        # DID we get form data
        email = form.email.data
        firstName = form.firstName.data
        lastName = form.lastName.data
        password = form.password.data
        phonenumber = form.phonenumber.data
        streetAddress = form.streetAddress.data
        bio = form.bio.data
        profile_picture_file = form.profilePicture.data
        profile_picture_path = None
        if profile_picture_file and getattr(profile_picture_file, 'filename', ''):
            filename = secure_filename(profile_picture_file.filename)
            if filename:
                upload_dir = os.path.join('club95', 'static', 'img')
                os.makedirs(upload_dir, exist_ok=True)
                save_path = os.path.join(upload_dir, filename)
                profile_picture_file.save(save_path)
                profile_picture_path = os.path.join('img', filename).replace('\\', '/')

        # DOES the user already exists
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email address already exists', 'registration_email_error')
            return redirect(url_for('auth_bp.register'))
        # create new user with hashed password and add to db
        new_user = User(
            email=email,
            firstName=firstName,
            lastName=lastName,
            password=generate_password_hash(password, method='scrypt', salt_length=16),
            phoneNumber=phonenumber,
            bio=bio,
            streetAddress=streetAddress,
            profilePicture=profile_picture_path
        )
        db.session.add(new_user)
        db.session.commit()

        #return success and redirect to login page
        flash('Registration successful! Please log in.', 'registration_success')
        return redirect(url_for('auth_bp.login'))
    
    return render_template('/auth/register.html', form=form, heading="Register")

@auth_bp.route('/auth/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = None
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        # Find user by email
        u1 = User.query.filter_by(email=email).first()

        if u1 is None:
            error = 'Incorrect email.'
            flash(error, 'login_error')
            return redirect(url_for('auth_bp.login'))
        elif not check_password_hash(u1.password, password):
            error = 'Incorrect password.'
            flash(error, 'login_error')
            return redirect(url_for('auth_bp.login'))
        if error is None:
            login_user(u1)
            flash('Logged in successfully. Welcome back, ' + u1.firstName + '!', 'login_success')
            next_page = request.args.get('next')
            return redirect(next_page or url_for('home_bp.index'))
        else:
            print(error)
            flash(error, 'login_error')
    ## passed the gaunlets of checks and logged in
    return render_template('/auth/login.html', form=form, heading="Login")

## logout route - logs out user and redirects to homepage. thats it. thats all this does.
@auth_bp.route('/auth/logout')
def logout():
    logout_user()
    flash('You have been logged out.', 'logout-success')
    ## spits user back to homepage
    return redirect(url_for('home_bp.index'))
    

club95/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Boostrap and custom styles -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/styles.css')}}"
        />
        <meta charset="utf-8" />
        <meta name="description" content="Cl: center95" />
        <meta name="author" content="IAB207 Group 49" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Club95</title>
    </head>

    <body>
        <header>
            <!-- Navbar -->
            <!-- Collapse on viewports smaller than large -->
            <nav class="navbar navbar-expand-lg">
                <div
                    class="container-fluid d-flex justify-content-between position-relative"
                >
                    <!-- Website Icon (Placeholder) -->
                    <a
                        class="navbar-brand position-relative"
                        href="{{ url_for('home_bp.index') }}"
                    >
                        <img
                            src="{{ url_for('static', filename='img/cassette.png') }}"
                            alt="Logo"
                            width="50"
                            height="50"
                        />
                    </a>
                    <!-- Title -->
                    <div
                        class="navbar-title position-absolute start-50 translate-middle-x"
                    >
                        <a
                            class="navbar-brand"
                            href="{{ url_for('home_bp.index') }}"
                            >Club95</a
                        >
                    </div>
                    <!-- Toggle button to show/hide navbar on smaller viewports -->
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbar-nav"
                        aria-controls="navbar-nav"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Collapsible part of the navbar -->
                    <!-- (elements are hidden are smaller viewports) -->
                    <div class="collapse navbar-collapse" id="navbar-nav">
                        <!-- Left side elements of navbar -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <!-- Home page link -->
                            <li class="nav-item">
                                <a
                                    class="nav-link active"
                                    aria-current="page"
                                    href="{{ url_for('home_bp.index') }}"
                                    >Home</a
                                >
                            </li>

                            <!-- welcome message for logged in user-->
                            {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('user_bp.profile') }}"
                                    >{{ (current_user.firstName ~ ' ' ~
                                    (current_user.lastName or '')) | trim }}
                                </a>
                            </li>
                            {% else %}

                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('auth_bp.login') }}"
                                    >Account</a
                                >
                            </li>

                            {% endif %}
                            <!-- Help menu -->
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('home_bp.faq') }}"
                                >
                                    FAQ
                                </a>
                            </li>
                        </ul>
                        <!-- Right side elements of navbar -->
                        <ul class="navbar-nav me-2 mb-auto mb-lg-0">
                            {% if current_user.is_authenticated %}
                            <li class="nav-item" .createevent>
                                <a
                                    class="nav-link"
                                    href="{{ url_for('events_bp.createevent') }}"
                                    >Create Event</a
                                >
                            </li>
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('events_bp.myevents') }}"
                                >
                                    My Events
                                </a>
                            </li>
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('user_bp.mytickets') }}"
                                    >My Tickets</a
                                >
                            </li>
                            {% endif %} {% if not current_user.is_authenticated
                            %}
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('auth_bp.login') }}"
                                    >Sign In</a
                                >
                            </li>
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('auth_bp.register') }}"
                                    >Register</a
                                >
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ url_for('auth_bp.logout') }}"
                                    >Sign Out</a
                                >
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Navbar ends -->
        </header>

        <main>
            <h1 id="heading">{{ heading }}</h1>
            {% block body %} {% endblock %}
        </main>

        <footer>
            <!-- Social media buttons -->
            <div
                class="container-fluid"
                id="social-container"
                style="margin-top: 3rem"
            >
                <!-- Facebook -->
                <a class="btn btn-floating m-1" href="#!" role="button">
                    <img
                        src="{{ url_for('static', filename='img/facebook.png') }}"
                        alt="Facebook logo button"
                        height="35"
                        width="35"
                    />
                </a>

                <!-- Youtube -->
                <a class="btn btn-floating m-1" href="#!" role="button">
                    <img
                        src="{{ url_for('static', filename='img/youtube.png') }}"
                        alt="Youtube logo button"
                        height="35"
                        width="35"
                    />
                </a>

                <!-- Github -->
                <a class="btn btn-floating m-1" href="#!" role="button">
                    <img
                        src="{{ url_for('static', filename='img/github.svg') }}"
                        alt="Github logo button"
                        height="35"
                        width="35"
                    />
                </a>
            </div>

            <!-- Copyright -->
            <div class="container-fluid" id="copyright-bar">
                <div class="p-2">
                    &copy; 2025 Copyright: Nathan Pithie, Ananya Aastha, Bryn
                    McCulloch
                </div>
            </div>
        </footer>

        <!-- Boostrap JS -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

<script>
    window.addEventListener("load", () => {
        const el = document.querySelector(".flash-container");
        if (el) el.classList.add("expand");
    });
</script>

club95/templates/error.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}

{% block body %}
    <div class="error-page-container">
        <h1 class="error-code">Error {{ error.code }}</h1>
        <p class="error-message">{{ error.description }}</p>
    {% if error.code == 404 %}
    <p class="error-suggestion">Please check the URL or return to the home page.</p>
    {% elif error.code == 500 %}
    <p class="error-suggestion">An unexpected error occurred. Please try again later.</p>
    {% elif error.code == 403 %}
    <p class="error-suggestion">You do not have permission to access this resource.</p>
    {% elif error.code == 400 %}
    <p class="error-suggestion">Bad request. Please check your input and try again.</p>
    {% elif error.code == 401 %}
    <p class="error-suggestion">Unauthorized access. Please log in and try again.</p>
    {% elif error.code == 405 %}
    <p class="error-suggestion">Method not allowed for this resource. Try using a different action.</p>
    {% elif error.code == 408 %}
    <p class="error-suggestion">Request timed out. Please try again later.</p>
    {% elif error.code == 429 %}
    <p class="error-suggestion">Too many requests. Please wait a moment before trying again.</p>
    {% elif error.code == 503 %}
    <p class="error-suggestion">Service unavailable. Please try again later.</p>
    {% elif error.code == 502 %}
    <p class="error-suggestion">Bad gateway. The server received an invalid response. Please try again soon.</p>
    {% elif error.code == 504 %}
    <p class="error-suggestion">Gateway timeout. The upstream server took too long to respond.</p>
    {% elif error.code == 415 %}
    <p class="error-suggestion">Unsupported file type. Please upload a supported format and retry.</p>
    {% elif error.code == 422 %}
    <p class="error-suggestion">We could not process the data provided. Please review your input and submit again.</p>
    {% elif error.code is none or error.code is undefined %}
    <p class="error-suggestion">An unexpected error occurred. Please try again later.</p>
    {% endif %}
        <a href="{{ url_for('home_bp.index') }}" class="btn btn-primary mt-3">Return to Home Page</a>
    </div>
{% endblock %}

club95/templates/forms.html
{% include "base.html" % %} {% import bootstrap from "bootstrap/wtf.html" %} {%
block body %}

<div class="page-header">
    <h4>{{ heading }}</h4>
</div>

{% with messages = get_flashed_messages() %} {% if messages %} {% for category,
message in messages %}
<div class="alert alert success">
    {{ message }}
    <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
    ></button>
</div>
{% endfor %} {% endif %} {% endwith %}

<div class="col-md-6">{{wtf.quick_form(form)}}</div>

<!-- checks if heading function was called from-->
{% if heading|lower == 'create event'%}
<div class="col-md-4">
    <p>
        New user?
        <a href="{{ url_for('auth.register') }}">click here to register</a>
    </p>
</div>
" {% endif %} {% endblock %}

club95/templates/index.html
{% extends "base.html" %} {% from "partials/search_filters.html" import
render_search_filters %} {% block body %}

<!-- prettier-ignore -->
<div class="main-window">
    {% if upcoming_events %}
    <div class="container mb-4" id="upcoming-events-window-container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10">
                <div class="window" id="upcoming-events-window">
                    <div class="title-bar">
                        <span class="window-title">Upcoming Events</span>
                        <div class="window-controls">
                            <button type="button" class="btn" href="#!">_</button>
                            <button type="button" class="btn" href="#!">☐</button>
                            <button type="button" class="btn" id="closebtn" href="#!">X</button>
                        </div>
                    </div>
                    <div class="sub-window">
                        <div id="upcomingEventsCarousel" class="carousel slide" data-bs-ride="carousel">
                            {% if upcoming_events|length > 1 %}
                            <div class="carousel-indicators">
                                {% for event in upcoming_events %}
                                <button type="button" data-bs-target="#upcomingEventsCarousel" data-bs-slide-to="{{ loop.index0 }}" class="{% if loop.first %}active{% endif %}" {% if loop.first %}aria-current="true"{% endif %} aria-label="Slide {{ loop.index }}"></button>
                                {% endfor %}
                            </div>
                            {% endif %}
                            <div class="carousel-inner">
                                {% for event in upcoming_events %}
                                {% set poster_src = url_for('static', filename='img/' ~ event.image) if event.image else url_for('static', filename='img/fallback.jpg') %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <a href="{{ url_for('events_bp.eventdetails', event_id=event.id) }}" class="d-block position-relative">
                                        <img src="{{ poster_src }}" class="d-block w-100 img-fit" alt="{{ event.title }} poster" />
                                        <div class="carousel-caption d-none d-md-block bg-dark bg-opacity-50 rounded py-2 px-3">
                                            <h5 class="mb-1">{{ event.title }}</h5>
                                            {% set event_date = event.date or 'Coming Soon' %}
                                            <p class="mb-0">{{ event_date }}</p>
                                        </div>
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                            {% if upcoming_events|length > 1 %}
                            <button class="carousel-control-prev" type="button" data-bs-target="#upcomingEventsCarousel" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#upcomingEventsCarousel" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {{ render_search_filters(
    search_term=search_term|default(''),
    search_url='home_bp.search',
    event_types=(filter_event_types | map(attribute='typeName') | list),
    genres=(filter_genres | map(attribute='genreType') | list),
    statuses=filter_statuses
) }}

    <!-- Events List Section -->
    <!-- Events are listed inside 'windows' that include all
        their promotional material. 3 event windows per row on large viewports. -->
    <section class="events-list-page">
        <!-- Events Page Container -->

        <!-- prettier-ignore -->
    <div class="container" id="events-page-container">
        {% if search_term is defined and search_term %}
        <div class="alert alert-info mt-4" role="alert">
            Showing results for: <strong>{{ search_term }}</strong>
        </div>
        {% endif %}
        {# Flash message section #} 
                {% with messages = get_flashed_messages(category_filter=['login_success']) %} 
                    {% if messages %}
                    <div class="flash-hover">
                        <div class="flash-container">
                            <div class="success">
                                {% for message in messages %}
                                    <span>{{ message }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %} 
                {% endwith %}
                
                {% with messages = get_flashed_messages(category_filter=['logout-success']) %} 
                {% if messages %}
                    <div class="flash-hover">
                        <div class="flash-container">
                            <div class="success">
                                {% for message in messages %}
                                    <span>{{ message }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %} 
                {% endwith %} 

                {% with messages = get_flashed_messages(category_filter=['search_info']) %} 
                    {% if messages %}
                        <div class="alert alert-info mt-4" role="alert">
                            {% for message in messages %}
                                <span>{{ message }}</span>
                            {% endfor %}
                        </div>
                    {% endif %} 
                {% endwith %} 

            <div class="row align-items-center">
                {# Event cards #}
                {% for event in events %}
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="window" id="event-{{ event.id }}">
                        <div class="title-bar">
                            <span class="window-title">{{ event.title }}</span>
                            <div class="window-controls">
                                <button type="button" class="btn" href="#!">
                                    _
                                </button>
                                <button type="button" class="btn" href="#!">
                                    ☐
                                </button>
                                <button
                                    type="button"
                                    class="btn"
                                    id="closebtn"
                                    href="#!"
                                >
                                    X
                                </button>
                            </div>
                        </div>
                        <div class="sub-window">
                            <img
                                src="{{ url_for('static', filename='img/' ~ event.image) if event.image else url_for('static', filename='img/fallback.jpg') }}"
                                alt="{{ event.title }}"
                                class="window-img-top img-fit"
                            />
                            <section class="window-tags">
                                {% set event_type_label =
                                event.event_type.typeName if event.event_type
                                else 'Unassigned' %}
                                <span class="badge" id="event-type"
                                    >{{ event_type_label }}</span
                                >
                                <span
                                    class="badge"
                                    id="event-status-{{ event.status|lower|replace(' ', '-') }}"
                                >
                                    {{ event.status }}
                                </span>
                            </section>
                            <!-- prettier-ignore -->
                            <p class="sub-window-content">
                                {{ event.description or "Description coming
                                soon." }}
                                <br /><br />

                                {# Get lowest priced ticket #}
                                {% set min_ticket = event.tickets|min(attribute='price') if event.tickets else None %}
                                <strong>> PRICE:</strong> 
                                {% if min_ticket %}
                                    {% if min_ticket.price == 0 %}
                                        Free Entry
                                    {% else %}
                                        Starting at ${{ '%.2f'|format(min_ticket.price) }}
                                    {% endif %}
                                {% else %}
                                    N/A
                                {% endif %}
                                <br />

                                {# Get artists #}
                                <strong>> ARTIST LINEUP:</strong>
                                {% if event.artists %}
                                    {{ event.artists | map(attribute='artistName') | join(', ') }}
                                {% else %}
                                    TBA
                                {% endif %}
                                <br />

                                {% set venue_label = event.venue.location if event.venue else 'TBA' %}
                                <strong>> VENUE:</strong> {{ venue_label }}
                                <br />
                                
                                <strong>> DATE:</strong> {{ event.date or "TBA" }}
                                <br />

                                <strong>> TIME:</strong> {{ event.start_time or
                                "TBA" }}{% if event.end_time %}-{{
                                event.end_time }}{% endif %}<br />
                                <strong>> GENRES:</strong>
                                {% if event.genres %} {% for g in event.genres
                                %}
                                <a class="genre-search-link" href="{{ url_for('home_bp.search', search=g.genreType) }}">{{ g.genreType }}</a>{% if not
                                loop.last %}, {% endif %} {% endfor %} {% else
                                %}
                                <span>N/A</span>
                                {% endif %}
                            </p>
                            <a
                                class="btn"
                                id="view-details-btn"
                                href="{{ url_for('events_bp.eventdetails', event_id=event.id) }}"
                            >
                                View details
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- End of Events Page Container -->
    </section>
    <!-- End of Events List Section -->
</div>
{% endblock %}